{
 "title": "OpenSearch Prometheus",
 "description": "OpenSearch metrics for OpenSearch Prometheus Exporter and cadvisor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "index",
    "query": {
     "query": "opensearch_index_doc_number{context=\"total\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_status) / count(opensearch_cluster_nodes_number)"
    }
   ]
  },
  {
   "title": "Running Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_nodes_number) / count(opensearch_cluster_nodes_number)"
    }
   ]
  },
  {
   "title": "Active Data Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_datanodes_number) / count(opensearch_cluster_datanodes_number)"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_pending_tasks_number) / count(opensearch_cluster_pending_tasks_number)"
    }
   ]
  },
  {
   "title": "Breaker Tripped?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_circuitbreaker_tripped_count) / count(opensearch_circuitbreaker_tripped_count)"
    }
   ]
  },
  {
   "title": "Indexing Throttled?",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opensearch_indices_indexing_is_throttled_bool"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{type=\"active\"}) / count(opensearch_cluster_shards_number{type=\"active\"})"
    }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{type=\"active_primary\"}) / count(opensearch_cluster_shards_number{type=\"active_primary\"})"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{type=\"initializing\"}) / count(opensearch_cluster_shards_number{type=\"initializing\"})"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{type=\"relocating\"}) / count(opensearch_cluster_shards_number{type=\"relocating\"})"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opensearch_cluster_shards_number{type=\"unassigned\"}) / count(opensearch_cluster_shards_number{type=\"unassigned\"})"
    }
   ]
  },
  { "title": "Searches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Search Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(opensearch_index_search_query_count{index=\"$index\",context=\"total\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time Spent Servicing Search Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "rate(opensearch_index_search_query_time_seconds{index=\"$index\",context=\"total\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Search Fetch Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(opensearch_index_search_fetch_count{index=\"$index\",context=\"total\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time Spent Servicing Search Fetches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {
     "expr": "rate(opensearch_index_search_fetch_time_seconds{index=\"$index\",context=\"total\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Container Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "OpenSearch Process CPU usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "opensearch_process_cpu_percent", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"opensearch-cl.*-node.*\"}",
     "legendFormat": "mem usage: {{ name }}"
    },
    {
     "expr": "container_memory_working_set_bytes{name=~\"opensearch-cl.*-node.*\"}",
     "legendFormat": "working set: {{name}}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\"opensearch-cl.*-node.*\"}[30s])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=~\"opensearch-cl.*-node.*\"}[30s])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Disk Reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_blkio_device_usage_total{operation=\"Read\",name=~\"opensearch-cl.*-node.*\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_blkio_device_usage_total{operation=\"Write\",name=~\"opensearch-cl.*-node.*\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Caching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Field Data Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "opensearch_indices_fielddata_memory_size_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Field Data Eviction Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(opensearch_index_fielddata_evictions_count{index=\"$index\",context=\"total\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query Cache Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "rate(opensearch_index_querycache_cache_count{index=\"$index\",context=\"total\"}[1m])",
     "legendFormat": "cache count: {{instance}}"
    },
    {
     "expr": "rate(opensearch_index_querycache_hit_count{index=\"$index\",context=\"total\"}[1m])",
     "legendFormat": "hit count: {{instance}}"
    }
   ]
  },
  {
   "title": "Query Cache Miss & Total Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "rate(opensearch_index_querycache_miss_number{index=\"$index\",context=\"total\"}[1m])",
     "legendFormat": "miss: {{instance}}"
    },
    {
     "expr": "rate(opensearch_index_querycache_total_number{index=\"$index\",context=\"total\"}[1m])",
     "legendFormat": "total: {{instance}}"
    }
   ]
  },
  {
   "title": "Query Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "opensearch_indices_querycache_memory_size_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query Cache Evictions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(opensearch_index_querycache_evictions_count{index=\"$index\",context=\"total\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Thread Pools and the JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queue Depth by Thread Pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(opensearch_threadpool_tasks_number{name!=\"management\", type=\"queue\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "JVM Heap % Used",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "opensearch_jvm_mem_heap_used_bytes / opensearch_jvm_mem_heap_max_bytes",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Thread Pool Sizes (# of threads)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(opensearch_threadpool_threads_number{name!=\"management\", type=\"active\"}) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "JVM non-heap Mem Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "opensearch_jvm_mem_nonheap_used_bytes",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Thread pool rejections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(opensearch_threadpool_threads_count{name!=\"management\", type=\"rejected\"}[5m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "GC seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(opensearch_jvm_gc_collection_time_seconds[5m])",
     "legendFormat": "{{ gc }}"
    }
   ]
  },
  {
   "title": "Indexing Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total # Documents in the Index",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "opensearch_index_doc_number{index=\"$index\",context=\"total\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Documents Indexed Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "Documents / sec" }
   ],
   "targets": [
    {
     "expr": "rate(opensearch_indices_indexing_index_count[1m])",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Index Size in Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 92 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "opensearch_indices_store_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Translog Uncommitted Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(index) (opensearch_index_translog_uncommitted_size_bytes{context=\"primaries\",index=\"$index\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Merges - rate of segment merges / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opensearch_index_merges_current_number{index=\"$index\",context=\"total\"}",
     "legendFormat": "{{instance}} {{context}}"
    }
   ]
  },
  {
   "title": "OpenSearch Translog Flushes (right axis units?)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(opensearch_index_flush_total_count{index=\"$index\",context=\"total\"}[1m])",
     "legendFormat": "Flush count: {{instance}}"
    },
    {
     "expr": "rate(opensearch_index_flush_total_time_seconds{index=\"$index\", context=\"total\"}[$__rate_interval])",
     "legendFormat": "Flush time: {{instance}}"
    }
   ]
  },
  {
   "title": "Index Merges - rate of bytes merged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "opensearch_index_merges_current_size_bytes{index=\"$index\",context=\"total\"}",
     "legendFormat": "{{instance}} {{context}}"
    }
   ]
  },
  {
   "title": "Index Refreshes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "rate(opensearch_index_refresh_total_count{index=\"$index\",context=\"total\"}[30s])",
     "legendFormat": "{{instance}} {{context}}"
    }
   ]
  },
  {
   "title": "# of Segments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "opensearch_index_segments_number{index=\"$index\", context=\"total\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time Spent Indexing (units?)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "rate(opensearch_indices_indexing_index_time_seconds[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}